name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v2
          with:
            version: 8.3.1

      - name: Install dependencies
        run: pnpm install

      - name: Perform testing
        run: pnpm test:ci --coverage

      - name: Perform build source
        run: pnpm build
